# Generated by Django 6.0.5 on 2026-06-24 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_alter_book_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='bookFile',
            new_name='book_file',
        ),
    ]
