# Generated by Django 6.0.5 on 2026-06-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_rename_bookfile_book_book_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(related_name='books', to='books.genre'),
        ),
    ]
